version: '3.8'

services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://socialman:password123@db:5432/socialman_db
      - UPLOAD_FOLDER=./static/uploads
      - SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - uploads_data:/app/static/uploads
    depends_on:
      - db
    networks:
      - socialman_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=socialman_db
      - POSTGRES_USER=socialman
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - socialman_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - uploads_data:/app/static/uploads:ro
    depends_on:
      - app
    networks:
      - socialman_network
    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data:

networks:
  socialman_network:
    driver: bridge